#!/bin/bash

echo -n 'Enter project name: '
read proj_name

cur_path=`pwd`
dir_path=`dirname $cur_path`
trg_path="$dir_path/$proj_name"

cp -r "$cur_path" "$trg_path"

pushd "$trg_path"

for src_file in `find . -name '*{{PROJ_NAME}}*'`; do
    dst_file=${src_file/\{\{PROJ_NAME\}\}/$proj_name}
    mv $src_file $dst_file
done

find . -type f ! -path ./RUN_ME_FIRST -exec sed -i "s/{{PROJ_NAME}}/$proj_name/g" {} \;

rm ./RUN_ME_FIRST
rm -rf .git

popd

echo Done.
